FROM node:14-alpine as build

WORKDIR /app

COPY package.json .
COPY package-lock.json .
COPY nuxt.config.prod.js /app/nuxt.config.js
RUN yarn install
COPY ./src /app/src
RUN yarn generate
RUN rm -rf node_modules

FROM alpine:3.7
WORKDIR /app
RUN apk --update --no-cache add nginx
COPY --from=build /app/dist/ /app/
ADD docker/rootfs /

EXPOSE 8001

CMD ["/usr/sbin/nginx"]
