version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxtjs
    hostname: nuxtjs
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    tty: true
